version: "3.8"

services:
  db:
    image: postgres:17
    container_name: crm-db
    restart: unless-stopped
    environment:
      # Leitura de variáveis de ambiente definidas no Easypanel
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-leadscrm}
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d leadscrm"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  webhook:
    image: node:18-alpine
    container_name: crm-webhook
    working_dir: /app/webhook
    volumes:
      - ./webhook:/app/webhook
    restart: unless-stopped
    environment:
      # Usa as mesmas variáveis do serviço db
      - DATABASE_URL=postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-leadscrm}
      # Combina variáveis do Easypanel
      - WEBHOOK_URL=${WEBHOOK_URL:-${EASYPANEL_PROJECT_URL}/api/lead-event}
      - EASYPANEL_PROJECT_URL=${EASYPANEL_PROJECT_URL}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
